language: php

php:
  - 5.3
  - 5.4

script:
  - phpunit tests/AllTests.php
  - pear package-validate package.xml
  - php scripts/phpcs CodeSniffer.php CodeSniffer --standard=PHPCS --report=summary -np
