sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - composer install
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then php bin/phpcs --config-set php_path php; fi
  - phpunit -d date.timezone=Australia/Sydney tests/AllTests.php
  - php bin/phpcs --no-cache --parallel=1
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TRAVIS_PHP_VERSION != "nightly" ]]; then pear package-validate package.xml; fi
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then php scripts/build-phar.php; fi
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then php phpcs.phar; fi
