sudo: false
language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm

  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: hhvm

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" && $TRAVIS_PHP_VERSION != "nightly" && $TRAVIS_PHP_VERSION != hhv* ]]; then phpenv config-add php5-testingConfig.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then phpenv config-add php7-testingConfig.ini; fi

script:
  - if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php scripts/phpcs --config-set php_path php; fi
  - phpunit tests/AllTests.php
  - php scripts/phpcs CodeSniffer.php CodeSniffer --standard=PHPCS --report=full -np
  - if [[ $TRAVIS_PHP_VERSION != hhv* && ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then pear package-validate package.xml; fi
  - if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php scripts/build-phar.php; fi
  - if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php phpcs.phar CodeSniffer.php CodeSniffer --standard=PHPCS --report=full -np; fi
